#!/usr/bin/env python3
"""Rebuild shared/avatar-manifest.js from disk and audit what is there.

Two jobs, deliberately together: the manifest must never claim a file
that isn't on disk, and the audit must be run on the SAME pass so the
numbers reported are the numbers shipped.

Poison check: any image whose md5 repeats more than 3 times across the
set is a platform default/logo graphic, not a profile photo (Instagram
serves its brand image for private accounts and to bulk scrapers). Those
are reported and, with --purge, deleted.
"""
import hashlib
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'assets' / 'avatars'
PURGE = '--purge' in sys.argv

txt = (ROOT / 'shared' / 'influencers-data.js').read_text(encoding='utf-8')
data = json.loads('[' + txt.split('[\n', 1)[1].rsplit('\n];', 1)[0] + ']')

hashes = {}
for p in sorted(OUT.glob('*.jpg')):
    b = p.read_bytes()
    if len(b) < 2048:                      # too small to be a real photo
        hashes[p] = 'TOOSMALL'
        continue
    hashes[p] = hashlib.md5(b).hexdigest()

counts = Counter(hashes.values())
bad = {h for h, n in counts.items() if h == 'TOOSMALL' or n > 3}
suspect = [p for p, h in hashes.items() if h in bad]
if suspect:
    print(f'!! {len(suspect)} suspect files (duplicate/logo/too-small)')
    for h in sorted(bad):
        n = counts[h]
        if n > 1:
            print(f'   hash {h[:12]} x{n}')
    if PURGE:
        for p in suspect:
            p.unlink()
        print(f'   purged {len(suspect)}')

manifest = {}
for rec in data:
    m = {}
    if (OUT / f"{rec['id']}-tt.jpg").exists():
        m['tt'] = 1
    if (OUT / f"{rec['id']}-ig.jpg").exists():
        m['ig'] = 1
    if m:
        manifest[rec['id']] = m

(ROOT / 'shared' / 'avatar-manifest.js').write_text(
    '/* Generated by scripts/audit-avatars.py — do not hand-edit. */\n'
    'var AVATAR_FILES = ' + json.dumps(manifest, separators=(',', ':')) + ';\n',
    encoding='utf-8')

total = len(data)
have = len(manifest)
missing = [r['id'] for r in data if r['id'] not in manifest]
print(f'coverage: {have}/{total} ({have*100//total}%) profiles have a local avatar')
print(f'  tt only: {sum(1 for m in manifest.values() if m.get("tt") and not m.get("ig"))}')
print(f'  ig only: {sum(1 for m in manifest.values() if m.get("ig") and not m.get("tt"))}')
print(f'  both:    {sum(1 for m in manifest.values() if m.get("ig") and m.get("tt"))}')
print(f'  missing: {len(missing)}')
if missing[:10]:
    print('  e.g. ' + ', '.join(missing[:10]))
