#!/usr/bin/env python3
"""Harvest Instagram profile photos into assets/avatars/<id>-ig.jpg.

Instagram is the source the page cannot reach at runtime (its CDN and
pages are CORS-blocked and unavatar's IG source 403s), but the profile
page's og:image IS served to plain server-side requests — so this pulls
each one down as a static asset. TikTok stays a runtime concern: the
page's unavatar chain already resolves TT avatars in the browser.

Writes shared/avatar-manifest.js mapping id -> {ig:1}.
Re-runnable: existing files are skipped, the manifest is rebuilt from disk.
"""
import html
import json
import re
import subprocess
import time
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'assets' / 'avatars'
OUT.mkdir(parents=True, exist_ok=True)
# Deliberately a SIMPLE UA: Instagram serves the og:image-rich page to
# unknown/preview-style agents and the login app-shell to full Chrome UAs.
UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'
OG_RE = re.compile(r'<meta property="og:image" content="([^"]+)"')

txt = (ROOT / 'shared' / 'influencers-data.js').read_text(encoding='utf-8')
data = json.loads('[' + txt.split('[\n', 1)[1].rsplit('\n];', 1)[0] + ']')


def fetch(url, timeout=20):
    """curl, not urllib: Instagram fingerprints clients and serves the
    login shell (no og:image) to urllib's header set, while curl's
    minimal headers get the real page."""
    p = subprocess.run(
        ['curl', '-sL', '--max-time', str(timeout), '-A', UA,
         '-w', '\n%{http_code}\t%{content_type}', url],
        capture_output=True)
    if p.returncode != 0:
        raise RuntimeError('curl failed')
    body, _, tail = p.stdout.rpartition(b'\n')
    code, _, ctype = tail.decode('ascii', 'ignore').partition('\t')
    return int(code or 0), ctype, body


ok = miss = err = have = 0
for i, rec in enumerate(data):
    handles = {p['platform']: p['handle'] for p in rec.get('platforms', []) if p.get('handle')}
    h = handles.get('instagram')
    if not h:
        continue
    path = OUT / f"{rec['id']}-ig.jpg"
    if path.exists():
        have += 1
        continue
    try:
        status, ctype, body = fetch(f'https://www.instagram.com/{urllib.parse.quote(h)}/')
        m = OG_RE.search(body.decode('utf-8', 'ignore')) if status == 200 else None
        if not m:
            miss += 1
        else:
            status, ctype, body = fetch(html.unescape(m.group(1)))
            if status == 200 and ctype.startswith('image/') and len(body) > 500:
                path.write_bytes(body)
                ok += 1
            else:
                miss += 1
    except Exception:
        err += 1
    time.sleep(0.5)
    if (i + 1) % 25 == 0:
        print(f'{i + 1}/{len(data)} — ok:{ok} have:{have} miss:{miss} err:{err}', flush=True)

# Purge Instagram's default/logo image: private accounts get the brand
# graphic as og:image, so any hash shared by many files is not a real
# profile photo. Delete those before building the manifest.
import hashlib  # noqa: E402
from collections import Counter  # noqa: E402
hashes = {}
for p in OUT.glob('*-ig.jpg'):
    hashes[p] = hashlib.md5(p.read_bytes()).hexdigest()
common = {h for h, n in Counter(hashes.values()).items() if n > 3}
purged = 0
for p, h in hashes.items():
    if h in common:
        p.unlink()
        purged += 1
if purged:
    print(f'purged {purged} default-logo images', flush=True)

manifest = {}
for rec in data:
    if (OUT / f"{rec['id']}-ig.jpg").exists():
        manifest[rec['id']] = {'ig': 1}

(ROOT / 'shared' / 'avatar-manifest.js').write_text(
    '/* Generated by scripts/harvest-avatars.py — do not hand-edit. */\n'
    'var AVATAR_FILES = ' + json.dumps(manifest, separators=(',', ':')) + ';\n',
    encoding='utf-8')
print(f'manifest: {len(manifest)} profiles with an IG photo '
      f'(new:{ok} existing:{have} miss:{miss} err:{err})')
