#!/usr/bin/env python3
"""Harvest TikTok profile AVATARS into assets/avatars/<id>-tt.jpg.

Same source as harvest-posts.py — the public embed widget at
tiktok.com/embed/@handle — but keeping the '-avt-' CDN URLs that the
post harvester filters out. This removes the page's runtime dependency
on unavatar.io, which rate-limits (429) under any real load and left
most cards showing initials.

Signed URLs expire in ~48h, so images are downloaded (resized to 240px
with sips — displayed at 64px, so 240 covers retina) rather than
hotlinked. Requires the Referer header like the post covers do.

Rebuilds shared/avatar-manifest.js from disk (-tt and -ig files both).
Re-runnable: profiles with an existing -tt.jpg are skipped.
"""
import json
import re
import subprocess
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'assets' / 'avatars'
OUT.mkdir(parents=True, exist_ok=True)
UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'

txt = (ROOT / 'shared' / 'influencers-data.js').read_text(encoding='utf-8')
data = json.loads('[' + txt.split('[\n', 1)[1].rsplit('\n];', 1)[0] + ']')


def curl(url, extra=None):
    cmd = ['curl', '-sL', '--max-time', '20', '-A', UA,
           '-w', '\n%{http_code}\t%{content_type}']
    if extra:
        cmd += extra
    cmd.append(url)
    p = subprocess.run(cmd, capture_output=True)
    if p.returncode != 0:
        return 0, '', b''
    body, _, tail = p.stdout.rpartition(b'\n')
    code, _, ctype = tail.decode('ascii', 'ignore').partition('\t')
    return int(code or 0), ctype, body


def avatar_urls(handle):
    status, _, body = curl('https://www.tiktok.com/embed/@' + handle)
    if status != 200:
        return []
    text = body.decode('utf-8', 'ignore').replace('\\u002F', '/').replace('\\/', '/')
    urls = re.findall(r'https:[^"\'\\]*tiktokcdn[^"\'\\]*', text)
    out, seen = [], set()
    for u in urls:
        if '-avt-' not in u and 'avatar' not in u:
            continue
        key = u.split('?')[0].rsplit('/', 1)[-1].split('~')[0]
        if key in seen:
            continue
        seen.add(key)
        out.append(u)
    return out


def download(url, path):
    status, ctype, body = curl(url, extra=['-H', 'Referer: https://www.tiktok.com/'])
    if status == 200 and ctype.startswith('image/') and body[:2] == b'\xff\xd8':
        path.write_bytes(body)
        subprocess.run(['sips', '-Z', '240', str(path)], capture_output=True)
        return True
    return False


ok = miss = have = 0
for i, rec in enumerate(data):
    handles = {p['platform']: p['handle'] for p in rec.get('platforms', []) if p.get('handle')}
    h = handles.get('tiktok')
    if not h:
        continue
    path = OUT / f"{rec['id']}-tt.jpg"
    if path.exists():
        have += 1
        continue
    got = False
    for u in avatar_urls(h):
        if download(u, path):
            got = True
            break
    if got:
        ok += 1
    else:
        miss += 1
    time.sleep(1.0)
    if (i + 1) % 25 == 0:
        print(f'{i + 1}/{len(data)} — ok:{ok} have:{have} miss:{miss}', flush=True)

manifest = {}
for rec in data:
    m = {}
    if (OUT / f"{rec['id']}-tt.jpg").exists():
        m['tt'] = 1
    if (OUT / f"{rec['id']}-ig.jpg").exists():
        m['ig'] = 1
    if m:
        manifest[rec['id']] = m

(ROOT / 'shared' / 'avatar-manifest.js').write_text(
    '/* Generated by scripts/harvest-tt-avatars.py — do not hand-edit. */\n'
    'var AVATAR_FILES = ' + json.dumps(manifest, separators=(',', ':')) + ';\n',
    encoding='utf-8')
print(f'manifest: {len(manifest)} profiles with a local avatar '
      f'(new:{ok} existing:{have} miss:{miss})')
