#!/usr/bin/env python3
"""Harvest TikTok POST images (video covers / photo posts) per profile.

Source: the public embed widget at tiktok.com/embed/@handle — the one
surface TikTok serves without bot-gating, because it exists to be
iframed into third-party sites. Its embedded state carries signed
tiktokcdn.com URLs for recent post covers; the signatures expire in
~48h, so images are downloaded into assets/posts/ (resized to 480px
with sips) rather than hotlinked.

Saves up to 2 per profile: <id>-p1.jpg, <id>-p2.jpg.
Writes shared/post-manifest.js mapping id -> saved count.
Re-runnable: profiles with an existing -p1.jpg are skipped.
"""
import json
import re
import subprocess
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'assets' / 'posts'
OUT.mkdir(parents=True, exist_ok=True)
UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'
MAX_PER = 2

txt = (ROOT / 'shared' / 'influencers-data.js').read_text(encoding='utf-8')
data = json.loads('[' + txt.split('[\n', 1)[1].rsplit('\n];', 1)[0] + ']')


def curl(url, extra=None):
    cmd = ['curl', '-sL', '--max-time', '20', '-A', UA,
           '-w', '\n%{http_code}\t%{content_type}']
    if extra:
        cmd += extra
    cmd.append(url)
    p = subprocess.run(cmd, capture_output=True)
    if p.returncode != 0:
        return 0, '', b''
    body, _, tail = p.stdout.rpartition(b'\n')
    code, _, ctype = tail.decode('ascii', 'ignore').partition('\t')
    return int(code or 0), ctype, body


def post_urls(handle):
    status, _, body = curl('https://www.tiktok.com/embed/@' + handle)
    if status != 200:
        return []
    text = body.decode('utf-8', 'ignore').replace('\\u002F', '/').replace('\\/', '/')
    urls = re.findall(r'https:[^"\'\\]*tiktokcdn[^"\'\\]*', text)
    seen, out = set(), []
    for u in urls:
        if '-avt-' in u or 'avatar' in u:
            continue
        if '-p-' not in u and 'photomode' not in u:
            continue
        key = u.split('?')[0].rsplit('/', 1)[-1].split('~')[0]
        if key in seen:
            continue
        seen.add(key)
        out.append(u)
    return out


def download(url, path):
    status, ctype, body = curl(url, extra=['-H', 'Referer: https://www.tiktok.com/'])
    if status == 200 and ctype.startswith('image/') and body[:2] == b'\xff\xd8':
        path.write_bytes(body)
        subprocess.run(['sips', '-Z', '480', str(path)],
                       capture_output=True)
        return True
    return False


ok = miss = have = 0
for i, rec in enumerate(data):
    handles = {p['platform']: p['handle'] for p in rec.get('platforms', []) if p.get('handle')}
    h = handles.get('tiktok')
    if not h:
        continue
    if (OUT / f"{rec['id']}-p1.jpg").exists():
        have += 1
        continue
    saved = 0
    for u in post_urls(h):
        if saved >= MAX_PER:
            break
        if download(u, OUT / f"{rec['id']}-p{saved + 1}.jpg"):
            saved += 1
    if saved:
        ok += 1
    else:
        miss += 1
    time.sleep(1.0)
    if (i + 1) % 25 == 0:
        print(f'{i + 1}/{len(data)} — ok:{ok} have:{have} miss:{miss}', flush=True)

manifest = {}
for rec in data:
    n = sum(1 for k in (1, 2) if (OUT / f"{rec['id']}-p{k}.jpg").exists())
    if n:
        manifest[rec['id']] = n

(ROOT / 'shared' / 'post-manifest.js').write_text(
    '/* Generated by scripts/harvest-posts.py — do not hand-edit. */\n'
    'var POST_FILES = ' + json.dumps(manifest, separators=(',', ':')) + ';\n',
    encoding='utf-8')
print(f'manifest: {len(manifest)} profiles with post images '
      f'(new:{ok} existing:{have} none-found:{miss})')
