#!/usr/bin/env python3
"""Regenerate shared/influencers-data.js from the KULT xlsx export.

Usage:  python3 scripts/xlsx-to-data.py [path-to-xlsx]
Default source: ~/Desktop/influencers_from_KULT.xlsx (sheet "in").

Card-facing fields and the sensitive block (address/email/phone/nric)
are kept in separate keys so the page can keep PII out of the grid.
"""
import json
import re
import sys
from pathlib import Path

import openpyxl

SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.home() / 'Desktop' / 'influencers_from_KULT.xlsx'
OUT = Path(__file__).resolve().parent.parent / 'shared' / 'influencers-data.js'


def clean(v):
    if v is None:
        return ''
    s = str(v).strip()
    return '' if s.lower() in ('none', 'nan', '-', '—') else s


def handle_of(v):
    s = clean(v)
    if not s:
        return ''
    s = s.split('?')[0].rstrip('/')
    if '/' in s:
        s = s.rsplit('/', 1)[-1]
    s = s.lstrip('@')
    return '' if s in ('-', '—', '_') else s


def followers_of(v):
    if v is None:
        return None
    if isinstance(v, (int, float)):
        return int(v)
    digits = re.sub(r'[^0-9]', '', str(v))
    return int(digits) if digits else None


wb = openpyxl.load_workbook(SRC, read_only=True)
ws = wb.active
rows = ws.iter_rows(values_only=True)
headers = [str(h) for h in next(rows)]
idx = {h: i for i, h in enumerate(headers)}

records = []
for r in rows:
    def col(name):
        i = idx.get(name)
        return r[i] if i is not None and i < len(r) else None

    name = clean(col('name'))
    if not name:
        continue

    platforms = []
    for key, label in (('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('xhs', 'Xiaohongshu')):
        h = handle_of(col(key + 'Handle'))
        f = followers_of(col(key + 'Followers'))
        link = clean(col(key + 'Link'))
        if h or f or link:
            platforms.append({'platform': key, 'label': label,
                              'handle': h, 'followers': f, 'link': link})

    niches = [n.strip() for n in re.split(r'[,/]| and ', clean(col('niche'))) if n.strip()]

    records.append({
        'id': 'inf-%03d' % (len(records) + 1),
        'name': name,
        'niches': niches,
        'category': clean(col('category')),
        'age': clean(col('age')),
        'gender': clean(col('gender')),
        'ethnicity': clean(col('ethnicity')),
        'location': clean(col('location')),
        'platforms': platforms,
        'pii': {
            'address': clean(col('address')),
            'email': clean(col('email')),
            'phone': clean(col('contactNumber')),
            'nric': clean(col('nric')),
        },
    })

records.sort(key=lambda x: x['name'].lower())

body = ',\n'.join(json.dumps(rec, ensure_ascii=False) for rec in records)
OUT.write_text(
    '/* Generated by scripts/xlsx-to-data.py — do not hand-edit.\n'
    '   Source: %s (%d influencers, sorted A-Z). */\n'
    'var INFLUENCERS = [\n%s\n];\n' % (SRC.name, len(records), body),
    encoding='utf-8')
print('wrote', OUT, len(records), 'records')
